In [1]:
import pandas as pd

resume_df = pd.read_csv("data/AI_Resume_Screening.csv")
jobs_df = pd.read_csv("data/Combined_Jobs_Final_5000.csv")

In [2]:
print("Resume dataset shape:", resume_df.shape)
print("Jobs dataset shape:", jobs_df.shape)

Resume dataset shape: (1000, 11)
Jobs dataset shape: (5000, 23)

In [3]:
print("Resume columns:")
print(resume_df.columns.tolist())

print("\nJobs columns:")
print(jobs_df.columns.tolist())

Resume columns:
['Resume_ID', 'Name', 'Skills', 'Experience (Years)', 'Education', 'Certifications', 'Job Role', 'Recruiter Decision', 'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)']

Jobs columns:
['Job.ID', 'Provider', 'Status', 'Slug', 'Title', 'Position', 'Company', 'City', 'State.Name', 'State.Code', 'Address', 'Latitude', 'Longitude', 'Industry', 'Job.Description', 'Requirements', 'Salary', 'Listing.Start', 'Listing.End', 'Employment.Type', 'Education.Required', 'Created.At', 'Updated.At']

In [4]:
resume_df.head()

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100

In [5]:
jobs_df.head()

,Job.ID,Provider,Status,Slug,Title,Position,Company,City,State.Name,State.Code,...,Industry,Job.Description,Requirements,Salary,Listing.Start,Listing.End,Employment.Type,Education.Required,Created.At,Updated.At
0,294845,2,open,lake-forest-il-knowledge-universe-site-director,Site Director @ Knowledge Universe,Site Director,Knowledge Universe,Lake Forest,Illinois,IL,...,NaN,Job Summary Knowledge Universe (KU) Site Direc...,NaN,NaN,30-03-2015,29-04-2015,Part-Time,Not Specified,2015-03-31 10:13:55 UTC,2015-03-31 10:13:55 UTC
1,265365,2,open,reno-nv-officeteam-administrative-assistant-26...,Administrative Assistant @ OfficeTeam,Administrative Assistant,OfficeTeam,Reno,Nevada,NV,...,NaN,Ref ID: 03110-118480Classification: Secretary/...,NaN,NaN,09-03-2015,08-04-2015,Seasonal/Temp,Not Specified,2015-03-10 10:08:36 UTC,2015-03-10 10:08:36 UTC
2,305868,2,open,chi-payment-systems-account-manager-305868,Account Manager @ CHI Payment Systems,Account Manager,CHI Payment Systems,NaN,NaN,NaN,...,NaN,"If you&rsquo;re energetic, motivated, hardwork...",NaN,NaN,06-04-2015,05-05-2015,Full-Time/Part-Time,High School Diploma,2015-04-07 10:23:20 UTC,2015-04-07 10:23:20 UTC
3,275898,2,open,aurora-il-river-front-chrysler-jeep-dodge-outs...,Outside Wholesale Sales Rep (PART-TIME) @ Rive...,Outside Wholesale Sales Rep (PART-TIME),River Front Chrysler Jeep Dodge,Aurora,Illinois,IL,...,NaN,OUTSIDE WHOLESALE SALES REP\r\n\r\nJob Respons...,NaN,NaN,16-03-2015,15-04-2015,Part-Time,Not Specified,2015-03-17 10:19:53 UTC,2015-03-17 10:19:53 UTC
4,263702,2,open,salt-lake-city-ut-captioncall-customer-service...,Customer Service Rep- Help People with Hearing...,Customer Service Rep- Help People with Hearing...,CaptionCall,Salt Lake City,Utah,UT,...,NaN,CaptionCall® Communication Assistant Imagi...,NaN,NaN,06-03-2015,05-04-2015,Full-Time/Part-Time,Not Specified,2015-03-07 10:18:08 UTC,2015-03-07 10:18:08 UTC

In [6]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Resume_ID               1000 non-null   int64
 1   Name                    1000 non-null   object
 2   Skills                  1000 non-null   object
 3   Experience (Years)      1000 non-null   int64
 4   Education               1000 non-null   object
 5   Certifications          726 non-null    object
 6   Job Role                1000 non-null   object
 7   Recruiter Decision      1000 non-null   object
 8   Salary Expectation ($)  1000 non-null   int64
 9   Projects Count          1000 non-null   int64
 10  AI Score (0-100)        1000 non-null   int64
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [7]:
jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job.ID              5000 non-null   int64
 1   Provider            5000 non-null   int64
 2   Status              5000 non-null   object
 3   Slug                5000 non-null   object
 4   Title               5000 non-null   object
 5   Position            5000 non-null   object
 6   Company             4886 non-null   object
 7   City                4993 non-null   object
 8   State.Name          4992 non-null   object
 9   State.Code          4992 non-null   object
 10  Address             2 non-null      object
 11  Latitude            5000 non-null   float64
 12  Longitude           5000 non-null   float64
 13  Industry            19 non-null     object
 14  Job.Description     4997 non-null   object
 15  Requirements        0 non-null      float64
 16  Salary              16 non-null     float64
 17  Listing.Start       4958 non-null   object
 18  Listing.End         4989 non-null   object
 19  Employment.Type     4999 non-null   object
 20  Education.Required  4981 non-null   object
 21  Created.At          5000 non-null   object
 22  Updated.At          5000 non-null   object
dtypes: float64(4), int64(2), object(17)
memory usage: 898.6+ KB

In [8]:
print("Resume missing values:")
print(resume_df.isnull().sum())

print("\nJobs missing values:")
print(jobs_df.isnull().sum())

Resume missing values:
Resume_ID                   0
Name                        0
Skills                      0
Experience (Years)          0
Education                   0
Certifications            274
Job Role                    0
Recruiter Decision          0
Salary Expectation ($)      0
Projects Count              0
AI Score (0-100)            0
dtype: int64

Jobs missing values:
Job.ID                   0
Provider                 0
Status                   0
Slug                     0
Title                    0
Position                 0
Company                114
City                     7
State.Name               8
State.Code               8
Address               4998
Latitude                 0
Longitude                0
Industry              4981
Job.Description          3
Requirements          5000
Salary                4984
Listing.Start           42
Listing.End             11
Employment.Type          1
Education.Required      19
Created.At               0
Updated.At               0
dtype: int64

In [9]:
print("Resume duplicate rows:", resume_df.duplicated().sum())
print("Jobs duplicate rows:", jobs_df.duplicated().sum())

Resume duplicate rows: 0
Jobs duplicate rows: 0

In [10]:
resume_df["Job Role"].value_counts()

Job Role
AI Researcher            257
Data Scientist           255
Cybersecurity Analyst    255
Software Engineer        233
Name: count, dtype: int64

In [11]:
jobs_df["Employment.Type"].value_counts()

Employment.Type
Part-Time              2026
Seasonal/Temp          1649
Full-Time/Part-Time    1006
Per Diem                253
Intern                   61
Full-Time                 3
Contract                  1
Name: count, dtype: int64

In [12]:
resume_df["Education"].value_counts()

Education
B.Sc      205
MBA       202
B.Tech    200
M.Tech    198
PhD       195
Name: count, dtype: int64

In [13]:
jobs_df["Education.Required"].value_counts(dropna=False)

Education.Required
Not Specified          3678
High School Diploma     872
Associate Degree        210
Bachelor's Degree       159
Master's Degree          62
NaN                      19
Name: count, dtype: int64

In [14]:
print("=== Resume Skills ===")
print(resume_df.loc[0, "Skills"])

print("\n=== Resume Certifications ===")
print(resume_df.loc[0, "Certifications"])

print("\n=== Job Title ===")
print(jobs_df.loc[0, "Title"])

print("\n=== Job Description ===")
print(jobs_df.loc[0, "Job.Description"])

=== Resume Skills ===
TensorFlow, NLP, Pytorch

=== Resume Certifications ===
nan

=== Job Title ===
Site Director @ Knowledge Universe

=== Job Description ===
Job Summary Knowledge Universe (KU) Site Directors are site leaders who inspire children and teachers alike to learn and grow. They are passionate about educational excellence, and confident teaching children and adults. They use our nationally recognized curriculum as a framework to create unique and engaging classroom experiences. They are committed to making their site successful and know that meaningful relationships with children, families, and their team are important to success. They are fully engaged, enthusiastic about their work, and eager to share their knowledge with others.  Job Responsibilities and Essential Functions These are the basic expectations for Site Directors. Of course, creative and new ways to meet or exceed expectations are encouraged, so long as the required essential functions are also met. •         supervision of children and staff  •         record keeping  •         licensing records and child files  •         lesson planning and implementation  •         maintenance of safe and welcoming classroom environment  •         building of relationships with the community and school  •         recruiting new students to the program  •         applicant must have strong organizational skills

In [15]:
resume_selected = resume_df[
    [
        "Skills",
        "Experience (Years)",
        "Education",
        "Certifications",
        "Projects Count",
        "Job Role" 
    ]
]

resume_selected.head(20)

,Skills,Experience (Years),Education,Certifications,Projects Count,Job Role
0,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,8,AI Researcher
1,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,1,Data Scientist
2,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,7,Cybersecurity Analyst
3,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,0,AI Researcher
4,"SQL, React, Java",4,PhD,NaN,9,Software Engineer
5,"Cybersecurity, Networking, Linux, Ethical Hacking",10,B.Tech,Google ML,5,Cybersecurity Analyst
6,"Networking, Cybersecurity, Ethical Hacking",4,M.Tech,AWS Certified,9,Cybersecurity Analyst
7,"TensorFlow, Pytorch, NLP",3,M.Tech,AWS Certified,7,AI Researcher
8,"Networking, Ethical Hacking",7,MBA,Deep Learning Specialization,3,Cybersecurity Analyst
9,"Python, TensorFlow, Pytorch, NLP",0,M.Tech,AWS Certified,1,AI Researcher
10,"SQL, Java, C++",1,PhD,Deep Learning Specialization,7,Software Engineer
11,"Cybersecurity, Ethical Hacking, Networking",0,MBA,Google ML,5,Cybersecurity Analyst
12,"Cybersecurity, Networking",0,M.Tech,Deep Learning Specialization,9,Cybersecurity Analyst
13,"SQL, C++, Java",4,B.Sc,Deep Learning Specialization,10,Software Engineer
14,"Pytorch, NLP",0,M.Tech,Deep Learning Specialization,5,AI Researcher
15,"Cybersecurity, Networking",1,PhD,Google ML,6,Cybersecurity Analyst
16,"SQL, Python",10,PhD,NaN,2,Data Scientist
17,"Linux, Networking, Cybersecurity, Ethical Hacking",3,B.Tech,NaN,6,Cybersecurity Analyst
18,"SQL, Python, Deep Learning",3,MBA,NaN,10,Data Scientist
19,"Machine Learning, SQL, Python",10,B.Tech,Deep Learning Specialization,9,Data Scientist

In [16]:
jobs_selected = jobs_df[
    [
        "Title",
        "Company",
        "Industry",
        "Job.Description",
        "Employment.Type",
        "Education.Required",
    ]
]

jobs_selected.head()

,Title,Company,Industry,Job.Description,Employment.Type,Education.Required
0,Site Director @ Knowledge Universe,Knowledge Universe,NaN,Job Summary Knowledge Universe (KU) Site Direc...,Part-Time,Not Specified
1,Administrative Assistant @ OfficeTeam,OfficeTeam,NaN,Ref ID: 03110-118480Classification: Secretary/...,Seasonal/Temp,Not Specified
2,Account Manager @ CHI Payment Systems,CHI Payment Systems,NaN,"If you&rsquo;re energetic, motivated, hardwork...",Full-Time/Part-Time,High School Diploma
3,Outside Wholesale Sales Rep (PART-TIME) @ Rive...,River Front Chrysler Jeep Dodge,NaN,OUTSIDE WHOLESALE SALES REP\r\n\r\nJob Respons...,Part-Time,Not Specified
4,Customer Service Rep- Help People with Hearing...,CaptionCall,NaN,CaptionCall® Communication Assistant Imagi...,Full-Time/Part-Time,Not Specified

In [17]:
resume_clean = resume_selected.copy()
jobs_clean = jobs_selected.copy()

In [18]:
resume_clean["Certifications"] = resume_clean["Certifications"].fillna("")

jobs_clean["Company"] = jobs_clean["Company"].fillna("Unknown")
jobs_clean["Industry"] = jobs_clean["Industry"].fillna("Not Specified")
jobs_clean["Job.Description"] = jobs_clean["Job.Description"].fillna("")
jobs_clean["Education.Required"] = jobs_clean["Education.Required"].fillna("Not Specified")
jobs_clean["Employment.Type"] = jobs_clean["Employment.Type"].fillna("Not Specified")

In [19]:
print("Resume missing values:")
print(resume_clean.isnull().sum())

print("\nJobs missing values:")
print(jobs_clean.isnull().sum())

Resume missing values:
Skills                0
Experience (Years)    0
Education             0
Certifications        0
Projects Count        0
Job Role              0
dtype: int64

Jobs missing values:
Title                 0
Company               0
Industry              0
Job.Description       0
Employment.Type       0
Education.Required    0
dtype: int64

In [20]:
import re 

def clean_text(text):
    text = str(text) #Convert anything to a string
    text = text.lower() #Convert to lowercase
    text = re.sub(r"[^a[a-z0-9\s]", " ", text) #Remove punctuation and special characters
    text = re.sub(r"\s+", " ", text).strip() #Remove extra spaces

    return text

In [21]:
print("Original:")
print(resume_clean.loc[0, "Skills"])

print("\nCleaned:")
print(clean_text(resume_clean.loc[0, "Skills"]))

Original:
TensorFlow, NLP, Pytorch

Cleaned:
tensorflow nlp pytorch

In [22]:
print("Original:")
print(jobs_clean.loc[0, "Job.Description"][:300])

print("\nCleaned:")
print(clean_text(jobs_clean.loc[0, "Job.Description"])[:300])

Original:
Job Summary Knowledge Universe (KU) Site Directors are site leaders who inspire children and teachers alike to learn and grow. They are passionate about educational excellence, and confident teaching children and adults. They use our nationally recognized curriculum as a framework to create unique a

Cleaned:
job summary knowledge universe ku site directors are site leaders who inspire children and teachers alike to learn and grow they are passionate about educational excellence and confident teaching children and adults they use our nationally recognized curriculum as a framework to create unique and en

In [23]:
resume_clean["Resume_Text"] = (
    resume_clean["Skills"] + " " + 
    resume_clean["Experience (Years)"].astype(str) + " years " +
    resume_clean["Education"] + " " + 
    resume_clean["Certifications"] + " " +
    resume_clean["Projects Count"].astype(str) + " projects"
)

In [24]:
jobs_clean["Job_Text"] = (
    jobs_clean["Title"] + " " +
    jobs_clean["Company"] + " " +
    jobs_clean["Job.Description"] + " " 
)

In [25]:
resume_clean["Resume_Text"] = resume_clean["Resume_Text"].apply(clean_text)

jobs_clean["Job_Text"] = jobs_clean["Job_Text"].apply(clean_text)

In [26]:
print("=== Resume Text ===")
print(resume_clean.loc[0, "Resume_Text"])

print("\n=== Job Text ===")
print(jobs_clean.loc[0, "Job_Text"])

=== Resume Text ===
tensorflow nlp pytorch 10 years b sc 8 projects

=== Job Text ===
site director knowledge universe knowledge universe job summary knowledge universe ku site directors are site leaders who inspire children and teachers alike to learn and grow they are passionate about educational excellence and confident teaching children and adults they use our nationally recognized curriculum as a framework to create unique and engaging classroom experiences they are committed to making their site successful and know that meaningful relationships with children families and their team are important to success they are fully engaged enthusiastic about their work and eager to share their knowledge with others job responsibilities and essential functions these are the basic expectations for site directors of course creative and new ways to meet or exceed expectations are encouraged so long as the required essential functions are also met supervision of children and staff record keeping licensing records and child files lesson planning and implementation maintenance of safe and welcoming classroom environment building of relationships with the community and school recruiting new students to the program applicant must have strong organizational skills